### ISSUE TITLE
请教问题-添加额外监控项

### ISSUE THREAD

**Issue by spygea** [nangongchengfeng/zabbix-api#4]
大佬您好，正在使用你的脚本，感谢奉献。
我想自己再加一些监控项，但是一直有报错。我在GetItems和SavetoExcel里都加了，请问还有哪里有问题啊？谢谢

Traceback (most recent call last):
  File "C:/Users/zabbix-api/Zabbix-api_v2/main.py", line 40, in <module>
    WriteExcel(file_name, zabbix_data)
  File "C:\Users\zabbix-api\Zabbix-api_v2\SaveToExcel.py", line 93, in WriteExcel
    HostItemValues.append(host['Version of Zabbix agent running'])
KeyError: 'Version of Zabbix agent running'

**Comment by spygea** [comment]
Fixed
